---
- hosts: localhost
  connection: local
  vars:
    app_name: notejam
  tasks:
    - name: Deploy CloudFormation stack
      cloudformation:
        state: present
        stack_name: "{{ app_name }}-{{ stage }}"
        region: "{{ region }}"
        template: cloudformation.yml
        template_parameters:
          Stage: "{{ stage }}"
          AMI: "{{ ami }}"
          AppName: "{{ app_name }}"
        tags:
          Application: "{{ app_name }}"
          Stage: "{{ stage }}"
      register: stack

    - name: Test deployment
      uri:
        url: "http://{{ stack.stack_outputs.DNSName }}"
        method: GET
      register: result
      until: 'result.status == 200'
      retries: 10
      delay: 30
