#!/usr/bin/env bash

set -euo pipefail

main() {
	mkdir -p tmp

	echo '~~~ Building code archive'
	git archive -v -o tmp/code.tar.gz HEAD rubyonrails/notejam

	echo '~~~ Building AMI w/packer'
	packer build -var 'code_archive=tmp/code.tar.gz' pipeline/packer.json
}

main "$@"
